# Generated by Django 2.2.1 on 2020-01-31 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mobno',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
