# Generated by Django 2.2.1 on 2020-01-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_mobno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobno',
            field=models.IntegerField(null=True),
        ),
    ]
