# Generated by Django 2.2.1 on 2020-01-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectqueue',
            name='acceptance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectqueue',
            name='dev_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='short_description',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
